<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="camera_length" value="0.01" />
    <xacro:property name="camera_width" value="0.1" />
    <xacro:property name="camera_height" value="0.05" />

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
            <material name="grey"/>
            <!-- origin is 0 0 0 -->
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
        </collision>
        <xacro:box_inertia mass="0.1" lenght="${camera_length}" width="${camera_width}" height="${camera_height}"
                           xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="camera_torso_joint" type="fixed">
        <parent link="torso_link"/>
        <child link="camera_link"/>
        <origin xyz="0 ${(torso_width + camera_length) / 2} ${torso_height / 2}" rpy="0 0 ${pi/2}"/>
    </joint>

</robot>