<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="torso_height" value="1" />
    <xacro:property name="torso_length" value="${0.7 * torso_height}" />
    <xacro:property name="torso_width" value="${0.5 * torso_height}" />
    <xacro:property name="pivot_radius" value="${0.15 * torso_height}" />
    <xacro:property name="leg_lenght" value="${torso_height / 2}" />
    <xacro:property name="leg_hip_offset" value="${-(leg_lenght / 2) + (pivot_radius * 0.25)}" />
    <xacro:property name="leg_ankle_offset" value="${-leg_lenght-pivot_radius*0.5}" />
    <xacro:property name="foot_height" value="${pivot_radius*1.25}" />
    <xacro:property name="foot_ankle_offset" value="${pivot_radius-(foot_height/2)}" />
    

    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${torso_length} ${torso_width} ${torso_height}" />
            </geometry>
            <origin xyz="0 0 ${torso_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
    </link>

    <xacro:macro name="pivot_link" params="prefix rpy">
        <link name="${prefix}_link">
            <visual>
                <geometry>
                    <cylinder radius="${pivot_radius}" length="${torso_width/4}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${rpy}" />
                <material name="grey" />
            </visual>
        </link>
    </xacro:macro>

    <xacro:pivot_link prefix="right_hip" rpy="0 ${pi/2.0} 0" />
    <xacro:pivot_link prefix="left_hip" rpy="0 ${pi/2.0} 0" />
    <xacro:pivot_link prefix="right_ankle" rpy="${pi/2.0} 0 0" />
    <xacro:pivot_link prefix="left_ankle" rpy="${pi/2.0} 0 0" />

    <link name="right_leg_link">
        <visual>
            <geometry>
                <cylinder radius="${torso_length*0.2}" length="${leg_lenght}" />
            </geometry>
            <origin xyz="0 0 ${leg_hip_offset}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
    </link>

    <link name="left_leg_link">
        <visual>
            <geometry>
                <cylinder radius="${torso_length*0.2}" length="${leg_lenght}" />
            </geometry>
            <origin xyz="0 0 ${leg_hip_offset}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
    </link>

    <link name="right_foot_link">
        <visual>
            <geometry>
                <box size="${torso_length*0.5/0.7} ${torso_width*1.1} ${foot_height}" />
            </geometry>
            <origin xyz="0 0 ${foot_ankle_offset}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
    </link>

    <link name="left_foot_link">
        <visual>
            <geometry>
                <box size="${torso_length*0.5/0.7} ${torso_width*1.1} ${foot_height}" />
            </geometry>
            <origin xyz="0 0 ${foot_ankle_offset}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
    </link>








    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${leg_lenght+foot_height+1.5*pivot_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="right_hip_joint" type="revolute">
        <parent link="base_link" />
        <child link="right_hip_link" />
        <origin xyz="${torso_length/2} 0 0" rpy="0 0 0"/>
        <axis xyz="-1 0 0" />
        <limit lower="${-pi/2.0}" upper="${pi/2.0}" velocity="100" effort="100" />
    </joint>

    <joint name="left_hip_joint" type="revolute">
        <parent link="base_link" />
        <child link="left_hip_link" />
        <origin xyz="${-torso_length/2} 0 0" rpy="0 0 0"/>
        <axis xyz="-1 0 0" />
        <limit lower="${-pi/2.0}" upper="${pi/2.0}" velocity="100" effort="100" />
    </joint>

    <joint name="right_leg_joint" type="fixed">
        <parent link="right_hip_link" />
        <child link="right_leg_link" />
        <origin xyz="0 0 -${pivot_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="left_leg_joint" type="fixed">
        <parent link="left_hip_link" />
        <child link="left_leg_link" />
        <origin xyz="0 0 -${pivot_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="right_ankle_joint" type="revolute">
        <parent link="right_leg_link" />
        <child link="right_ankle_link" />
        <origin xyz="0 0 ${leg_ankle_offset}" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
        <limit lower="-0.8" upper="0.8" velocity="100" effort="100" />
    </joint>

    <joint name="left_ankle_joint" type="revolute">
        <parent link="left_leg_link" />
        <child link="left_ankle_link" />
        <origin xyz="0 0 ${leg_ankle_offset}" rpy="0 0 0"/>
        <axis xyz="0 -1 0" />
        <limit lower="-0.8" upper="0.8" velocity="100" effort="100" />
    </joint>

    <joint name="right_foot_joint" type="fixed">
        <parent link="right_ankle_link" />
        <child link="right_foot_link" />
        <origin xyz="0 0 -${pivot_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="left_foot_joint" type="fixed">
        <parent link="left_ankle_link" />
        <child link="left_foot_link" />
        <origin xyz="0 0 -${pivot_radius}" rpy="0 0 0"/>
    </joint>

</robot>